### ISSUE TITLE
provide more detail of your project

### ISSUE THREAD

**Issue by sudhanshuptl** [SabrinaSimon/Text-Summarization#1]
please  provide information that what you gonna make .. it makes lot easy to understanding  your code .

**Comment by SabrinaSimon** [comment]
It was my final year project :) which is already done now... well it was supposed to summarize a large text roughly based on tf-idf algorithm.. though I didnt have enough time to make the front end properly and the code itself is quite rigid.. its not platform independent so if you want to run the code on your machine then the path needs to be redefined everywhere
